name: terraform provision
on: push

jobs:
  sg_provision:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::353075014684:role/Genpact-POC-PowerUser
          aws-region: us-east-1
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: terraform init
        run: |
          terraform init
      - name: terraform plan
        run: |
          terraform plan -out=tfplan
      - name: terraform plan output
        id: plan
        run: |
          echo "plan=tfplan" >> $GITHUB_OUTPUT
      - name: terraform apply
        id: sg
        run: |
          terraform apply ${{steps.plan.outputs.plan}}
      - name: Output sg
        id: sg
        run: |
          SG_ID=$(terraform output sg_id)
          echo "sg_id=SG_ID" >> $GITHUB_OUTPUT
      - name: print output sg
        run: |
          echo "SG id is: ${{steps.sg.outputs.sg_id}}"
