name: terraform provision
on:
  workflow_dispatch:
    inputs:
      creation:
        required: true
        options:
          - create
          - destroy
        default: create
        type: choice

jobs:
  sg_provision:
    if: inputs.creation == 'create'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      tf_plan: ${{steps.plan.outputs.plan}}
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::353075014684:role/Genpact-POC-PowerUser
          aws-region: us-east-1
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: terraform init
        run: |
          terraform init
      - name: terraform plan
        run: |
          terraform plan -out=tfplan
      - name: terraform plan output
        id: plan
        run: |
          echo "plan=tfplan" >> $GITHUB_OUTPUT
      - name: terraform apply
        id: sg
        run: |
          terraform apply ${{steps.plan.outputs.plan}}
      - name: Output sg
        id: sgid
        run: |
          SG_ID=$(terraform output -raw sg_id)
          echo "sg_id=$SG_ID" >> $GITHUB_OUTPUT
      - name: print output sg
        run: |
          echo "SG id is: ${{steps.sgid.outputs.sg_id}}"
  sg_destroy:
    runs-on: ubuntu-latest
    if: inputs.creation == 'destroy'
    permissions:
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::353075014684:role/Genpact-POC-PowerUser
          aws-region: us-east-1
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: terraform init
        run: terraform init
      - name: terraform destroy
        run: terraform destroy -auto-approve
